import { useEffect, useState } from 'react'
import { ArrowUpRight, ChevronRight, Inbox, Megaphone, X } from 'lucide-react'
import type { SosCategory, SosRequest } from '../data/sosRequests'

type AdvisoryType = 'Critical' | 'Warning' | 'Info'
type Advisory = { level: AdvisoryType; title: string; time: string; color: string }

const sosCategories: Array<'All' | SosCategory> = ['All', 'Medical', 'Flood assistance', 'Evacuation']
const advisories: Advisory[] = [
  { level: 'Critical', title: 'Typhoon AGHON: Signal #2', time: 'Sent 25 min ago', color: 'border-rose-500 bg-rose-500/7' },
  { level: 'Warning', title: 'Storm surge rising - Lapinig coast', time: 'Updated 14 min ago', color: 'border-amber-400 bg-amber-400/7' },
  { level: 'Info', title: 'Evacuation centers are open', time: 'Sent 1 hr ago', color: 'border-blue-400 bg-blue-400/7' },
  { level: 'Critical', title: 'Immediate evacuation: Lapinig shoreline', time: 'Sent 2 hr ago', color: 'border-rose-500 bg-rose-500/7' },
  { level: 'Warning', title: 'Heavy rainfall advisory for northern barangays', time: 'Sent 3 hr ago', color: 'border-amber-400 bg-amber-400/7' },
  { level: 'Info', title: 'Road access update: Baud-Pitogo route open', time: 'Updated 5 hr ago', color: 'border-blue-400 bg-blue-400/7' },
]
const advisoryTypes: Array<'All' | AdvisoryType> = ['All', 'Critical', 'Warning', 'Info']

function PanelHeader({ title, link, onClick }: { title: string; link: string; onClick?: () => void }) {
  return <div className="mb-3 flex items-center justify-between gap-3"><h2 className="font-display text-base font-semibold text-white">{title}</h2><button aria-label={`${link} ${title}`} className="flex items-center gap-1 text-xs font-semibold text-indigo-300 transition hover:text-indigo-200" onClick={onClick} type="button">{link}<ArrowUpRight className="size-3.5" /></button></div>
}

function SosRequestRow({ request, onSelect }: { request: SosRequest; onSelect: (id: string) => void }) {
  const Icon = request.icon
  return <button className="flex w-full items-center gap-3 rounded-xl px-2 py-2.5 text-left transition hover:bg-white/5 focus-visible:bg-white/5" onClick={() => onSelect(request.id)} type="button"><span className={`grid size-10 shrink-0 place-items-center rounded-xl ${request.color}`}><Icon className="size-[18px]" /></span><span className="min-w-0 flex-1"><span className="block truncate text-xs font-semibold text-slate-100">{request.name}</span><span className="mt-0.5 block truncate text-[10px] text-slate-500">{request.location} &middot; {request.type}</span><span className="mt-1 block font-mono text-[9px] text-slate-600">{request.received}</span></span><ChevronRight className="size-4 shrink-0 text-slate-600" /></button>
}

function AllSosRequestsDialog({ requests, onClose, onSelectRequest }: { requests: SosRequest[]; onClose: () => void; onSelectRequest: (id: string) => void }) {
  const [selectedCategory, setSelectedCategory] = useState<'All' | SosCategory>('All')
  useEffect(() => { const closeOnEscape = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose() }; window.addEventListener('keydown', closeOnEscape); return () => window.removeEventListener('keydown', closeOnEscape) }, [onClose])

  return <div className="fixed inset-0 z-[60] flex items-center justify-center bg-slate-950/70 p-4 backdrop-blur-sm" onMouseDown={onClose}><section aria-describedby="all-sos-description" aria-labelledby="all-sos-title" aria-modal="true" className="flex h-[620px] w-[680px] max-h-[calc(100svh-2rem)] max-w-[calc(100vw-2rem)] flex-col overflow-hidden rounded-2xl border border-white/15 bg-[#0b1222]/95 shadow-2xl shadow-black/60" onMouseDown={(event) => event.stopPropagation()} role="dialog"><header className="flex shrink-0 items-start justify-between gap-4 border-b border-white/10 px-5 py-4 sm:px-6"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-indigo-300">SOS monitoring</p><h2 className="mt-1 font-display text-lg font-semibold text-white" id="all-sos-title">All recent SOS requests</h2><p className="mt-1 text-xs text-slate-400" id="all-sos-description">{requests.length} requests, organized by assistance type.</p></div><button aria-label="Close all recent SOS requests" autoFocus className="grid size-9 shrink-0 place-items-center rounded-lg border border-white/10 text-slate-400 transition hover:bg-white/10 hover:text-white" onClick={onClose} type="button"><X className="size-4" /></button></header><div className="min-h-0 flex-1 space-y-5 overflow-y-auto p-5 sm:p-6"><div aria-label="Filter SOS requests by category" className="flex flex-wrap gap-2" role="group">{sosCategories.map((category) => <button aria-pressed={selectedCategory === category} className={`rounded-lg px-3 py-1.5 text-[11px] font-semibold transition ${selectedCategory === category ? 'bg-indigo-500/85 text-white shadow-sm shadow-indigo-950/50' : 'border border-white/10 bg-white/[0.035] text-slate-400 hover:bg-white/10 hover:text-slate-200'}`} key={category} onClick={() => setSelectedCategory(category)} type="button">{category}</button>)}</div>{sosCategories.filter((category): category is SosCategory => category !== 'All' && (selectedCategory === 'All' || category === selectedCategory)).map((category) => { const categoryRequests = requests.filter((request) => request.category === category); return <section key={category}><div className="mb-2.5 flex items-center justify-between"><h3 className="text-xs font-bold text-slate-200">{category}</h3><span className="rounded-full border border-white/10 bg-white/5 px-2 py-0.5 font-mono text-[10px] text-slate-400">{categoryRequests.length}</span></div><div className="space-y-1.5">{categoryRequests.map((request) => <SosRequestRow key={request.id} onSelect={onSelectRequest} request={request} />)}</div></section> })}</div></section></div>
}

function AllAdvisoriesDialog({ onClose }: { onClose: () => void }) {
  const [selectedType, setSelectedType] = useState<'All' | AdvisoryType>('All')
  useEffect(() => { const closeOnEscape = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose() }; window.addEventListener('keydown', closeOnEscape); return () => window.removeEventListener('keydown', closeOnEscape) }, [onClose])
  return <div className="fixed inset-0 z-[60] flex items-center justify-center bg-slate-950/70 p-4 backdrop-blur-sm" onMouseDown={onClose}><section aria-describedby="all-advisories-description" aria-labelledby="all-advisories-title" aria-modal="true" className="flex h-[620px] w-[680px] max-h-[calc(100svh-2rem)] max-w-[calc(100vw-2rem)] flex-col overflow-hidden rounded-2xl border border-white/15 bg-[#0b1222]/95 shadow-2xl shadow-black/60" onMouseDown={(event) => event.stopPropagation()} role="dialog"><header className="flex shrink-0 items-start justify-between gap-4 border-b border-white/10 px-5 py-4 sm:px-6"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-indigo-300">Advisory monitoring</p><h2 className="mt-1 font-display text-lg font-semibold text-white" id="all-advisories-title">All active advisories</h2><p className="mt-1 text-xs text-slate-400" id="all-advisories-description">{advisories.length} recent advisories, organized by type.</p></div><button aria-label="Close all active advisories" autoFocus className="grid size-9 shrink-0 place-items-center rounded-lg border border-white/10 text-slate-400 transition hover:bg-white/10 hover:text-white" onClick={onClose} type="button"><X className="size-4" /></button></header><div className="min-h-0 flex-1 space-y-5 overflow-y-auto p-5 sm:p-6"><div aria-label="Filter active advisories by type" className="flex flex-wrap gap-2" role="group">{advisoryTypes.map((type) => <button aria-pressed={selectedType === type} className={`rounded-lg px-3 py-1.5 text-[11px] font-semibold transition ${selectedType === type ? 'bg-indigo-500/85 text-white shadow-sm shadow-indigo-950/50' : 'border border-white/10 bg-white/[0.035] text-slate-400 hover:bg-white/10 hover:text-slate-200'}`} key={type} onClick={() => setSelectedType(type)} type="button">{type}</button>)}</div>{advisoryTypes.filter((type): type is AdvisoryType => type !== 'All' && (selectedType === 'All' || type === selectedType)).map((type) => { const typeAdvisories = advisories.filter((advisory) => advisory.level === type); return <section key={type}><div className="mb-2.5 flex items-center justify-between"><h3 className="text-xs font-bold text-slate-200">{type}</h3><span className="rounded-full border border-white/10 bg-white/5 px-2 py-0.5 font-mono text-[10px] text-slate-400">{typeAdvisories.length}</span></div><div className="space-y-2">{typeAdvisories.map((advisory) => <button className={`w-full border-l-[3px] ${advisory.color} rounded-r-xl px-3 py-3 text-left transition hover:translate-x-0.5 hover:brightness-125`} key={advisory.title} type="button"><span className="flex items-center gap-2 text-xs font-bold text-slate-100"><Megaphone className="size-3.5 text-slate-300" /> {advisory.title}</span><span className="mt-1.5 block font-mono text-[10px] text-slate-500">{advisory.level} &middot; {advisory.time}</span></button>)}</div></section> })}</div></section></div>
}

interface ResponsePanelsProps {
  requests: SosRequest[]
  onOpenSosRequest: (id: string) => void
}

export function ResponsePanels({ requests, onOpenSosRequest }: ResponsePanelsProps) {
  const [isAllSosOpen, setIsAllSosOpen] = useState(false)
  const [isAllAdvisoriesOpen, setIsAllAdvisoriesOpen] = useState(false)
  const recentSosRequests = requests.filter((request) => request.period === 'today')
  return <div className="space-y-5"><section className="panel p-5"><PanelHeader link="View all" onClick={() => setIsAllSosOpen(true)} title="Recent SOS requests" /><div aria-live="polite" className="space-y-1">{recentSosRequests.length > 0 ? recentSosRequests.map((request) => <SosRequestRow key={request.id} onSelect={onOpenSosRequest} request={request} />) : <div className="rounded-xl border border-dashed border-white/12 bg-white/[0.025] px-4 py-6 text-center"><Inbox className="mx-auto size-5 text-slate-500" /><p className="mt-2 text-xs font-semibold text-slate-300">No recent SOS requests found.</p></div>}</div></section><section className="panel p-5"><PanelHeader link="View all" onClick={() => setIsAllAdvisoriesOpen(true)} title="Active advisories" /><div className="space-y-2.5">{advisories.slice(0, 3).map((advisory) => <button className={`w-full border-l-[3px] ${advisory.color} rounded-r-xl px-3 py-3 text-left transition hover:translate-x-0.5 hover:brightness-125`} key={advisory.title} type="button"><span className="flex items-center gap-2 text-xs font-bold text-slate-100"><Megaphone className="size-3.5 text-slate-300" /> {advisory.title}</span><span className="mt-1.5 block font-mono text-[10px] text-slate-500">{advisory.level} &middot; {advisory.time}</span></button>)}</div></section>{isAllSosOpen && <AllSosRequestsDialog onClose={() => setIsAllSosOpen(false)} onSelectRequest={onOpenSosRequest} requests={requests} />}{isAllAdvisoriesOpen && <AllAdvisoriesDialog onClose={() => setIsAllAdvisoriesOpen(false)} />}</div>
}
